module.exports = {
    ru: {
        jump: (u) => `${u} заставил стримера прыгнуть!`,
        crouch: (u) => `${u} превратил стримера в гуся!`,
        god_on: (u) => `${u} возвысил стримера до небес! БЕССМЕРТИЕ ВКЛЮЧЕНО ⚡`,
        god_off: (u) => `${u} вернул стримера на землю. Смертность восстановлена 💀`,
        heal: (u, a) => `${u} подлечил стримера на ${a} HP! ❤️`,
        damage: (u, a) => `${u} нанес стримеру ${a} урона! 💢`,
        damage_god: (u) => `${u}, стример сейчас БОГ! Урон бессилен... 🛡️`,
        spawn: {
            Elsa: (u) => `${u} призвал милого пёсика!`,
            Tricycle: (u) => `${u} прикатил велосипед!`,
            Birthday: (u) => `${u} привел именинника!`,
            Tick: (u) => `${u} выпустил клеща!`,
            SlowMouth: (u) => `${u} вызывает рвоту!`,
            ThinMan: (u) => `${u} призвал слендера!`,
            Duck: (u) => `${u} призвал уточку!`,
            Thrower: (u) => `${u} призвал мелкого ублюдка!`,
            Animal: (u) => `${u} призвал животное!`,
            Upscream: (u) => `${u} отправил таракана!`,
            Hidden: (u) => `${u} призвал невидимку!`,
            Tumbler: (u) => `${u} заспавнил жабу!`,
            Bowtie: (u) => `${u} призвал мишлена!`,
            Floater: (u) => `${u} заспавнил пришельца!`,
            Spinny: (u) => `${u} заспавнил рулетку!`,
            HeartHugger: (u) => `${u} вырастил цветочек!`,
            HeadGrabber: (u) => `${u} натравил черта!`,
            Oogly: (u) => `${u} призвал комара!`,
            Hunter: (u) => `${u} заспавнил деда!`,
            Shadow: (u) => `${u} любит постарше...`,
            BombThrower: (u) => `${u} любит жвачку!`,
            Robe: (u) => `${u} призвал монашку!`,
            Runner: (u) => `${u} заспавнил куклу!`,
            Beamer: (u) => `${u} устроил вечеринку!`,
            Headman: (u) => `${u} призвал череп!`,
            Trudge: (u) => `${u} призвал демона!`,
        }
    },
    en: {
        jump: (u) => `${u} made the streamer jump!`,
        crouch: (u) => `${u} forced the streamer to crouch!`,
        god_on: (u) => `${u} granted the streamer IMMORTALITY! ⚡`,
        god_off: (u) => `${u} removed god mode. Mortality restored 💀`,
        heal: (u, a) => `${u} restored ${a} HP to the streamer! ❤️`,
        damage: (u, a) => `${u} dealt ${a} damage to the streamer! 💢`,
        damage_god: (u) => `${u}, the streamer is currently a GOD! Damage is useless... 🛡️`,
        spawn: {
            Elsa: (u) => `${u} summoned Elsa!`,
            Tricycle: (u) => `${u} sent the Tricycle!`,
            Birthday: (u) => `${u} invited the Birthday Boy!`,
            Tick: (u) => `${u} released a Tick!`,
            SlowMouth: (u) => `${u} summoned the Slow Mouth!`,
            ThinMan: (u) => `${u} summoned the Thin Man!`,
            Duck: (u) => `${u} sent the Duck!`,
            Thrower: (u) => `${u} summoned the Valuable Thrower!`,
            Animal: (u) => `${u} released the Animal!`,
            Upscream: (u) => `${u} sent an Upscream!`,
            Hidden: (u) => `${u} summoned the Hidden!`,
            Tumbler: (u) => `${u} sent the Tumbler!`,
            Bowtie: (u) => `${u} summoned the Bowtie!`,
            Floater: (u) => `${u} sent the Floater!`,
            Spinny: (u) => `${u} summoned the Spinny!`,
            HeartHugger: (u) => `${u} sent a Heart Hugger!`,
            HeadGrabber: (u) => `${u} unleashed the Head Grabber!`,
            Oogly: (u) => `${u} summoned the Oogly!`,
            Hunter: (u) => `${u} unleashed the Hunter!`,
            Shadow: (u) => `${u} summoned the Shadow!`,
            BombThrower: (u) => `${u} sent the Bomb Thrower!`,
            Robe: (u) => `${u} summoned the Robe!`,
            Runner: (u) => `${u} unleashed the Runner!`,
            Beamer: (u) => `${u} started the Beamer party!`,
            Headman: (u) => `${u} summoned the Headman!`,
            Trudge: (u) => `${u} summoned the Trudge!`,
        }
    }
};